apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-list-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-list-kustomize
  template:
    metadata:
      labels:
        app: image-list-kustomize
    spec:
      containers:
      - name: nginx
        image: nginx:latest
