apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: appset
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - appName: app1
            url: https://kubernetes.default.svc
            versionConstraint: "1.11.x"
          - appName: app2
            url: https://kubernetes.default.svc
            versionConstraint: "1.12.x"
  ignoreApplicationDifferences:
    - jsonPointers:
        - /spec/source/kustomize/images
  template:
    metadata:
      name: '{{appName}}'
      namespace: argocd
      annotations:
        argocd-image-updater.argoproj.io/image-list: nginx=nginx:{{versionConstraint}}
        argocd-image-updater.argoproj.io/update-strategy: semver
        argocd-image-updater.argoproj.io/force-update: "false"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      source:
        repoURL: https://github.com/chengfang/image-updater-examples.git
        path: appset/source/overlays/{{appName}}
        targetRevision: main
      destination:
        server: '{{url}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true