apiVersion: apps/v1
kind: Deployment
metadata:
  name: push-branch-kustomize
spec:
  replicas: 1
  selector:
    matchLabels:
      app: push-branch-kustomize
  template:
    metadata:
      labels:
        app: push-branch-kustomize
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.0
